### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Yayalel** [bowen-upenn/scene_graph_commonsense#5]
Dear author:
Thank you for sharing the project. During the replication process, I couldn't find two files (as shown in the figure below), which are two pre trained models that I couldn't find in the checkpoints download section. I hope you can add a download link.
I would greatly appreciate it if you could reply to me.
![figure1](https://github.com/bowen-upenn/scene_graph_commonsense/assets/116719193/26d8304c-cf17-403e-b188-2b7f4c52010c)
![figure2](https://github.com/bowen-upenn/scene_graph_commonsense/assets/116719193/bb9a6bd0-b4b0-4be5-a039-9167147d6acc)

**Comment by bowen-upenn** [comment]
Hi Yayalel. I am currently traveling for work and will be back office at the beginning of July. Sorry for the inconvenience.

**Comment by Yayalel** [comment]
Okay, thank you for your reply. If you have time to upload it after you come back, I would greatly appreciate it.

**Comment by Yayalel** [comment]
May I ask if your business trip has ended now? If it's convenient for you, could you please upload the file? I would greatly appreciate it.

**Comment by bowen-upenn** [comment]
Hello. May we know how urgent you need these two checkpoints? We find that these two checkpoints, which are relatively old, were not preserved during recent server updates, so we would need to retrain them to get their weights. However, these two models are only two of the intermediate ablation studies, rather than the final best-performing models we would recommend for either downstream applications or comparative studies in your own work.

**Comment by Yayalel** [comment]
Thank you for your reply. I understand what you mean. Currently, I am in the experimental stage and need to know the training results of the model with only hierarchical relationship classification. I am deeply sorry for the inconvenience caused to you and sincerely hope that you can upload two pre trained models after retraining. Regarding the urgency level, I would like to complete the entire experiment within a month, but everything will be based on your schedule.

**Comment by bowen-upenn** [comment]
I think the model with a flat classification head + commonsense validation has already been uploaded, and you can find it on README: https://drive.google.com/file/d/1nwN8ToqfcRfabtf5PcJLAzd0J-Ky-6s3/view?usp=sharing. The saved model name might be different, so please try with this one first and rename it if needed. 

Currently, we are busy with several upcoming submissions and there are no more GPU resources available in our group, but you can follow our README to train your baseline model with a flat classification head and without the commonsense validation step. 

Apologize for the inconvenience and thank you so much for your understanding.

**Comment by Yayalel** [comment]
Okay, thank you very much for your patient reply.
